# config for ldap-find-orphans.rb

# Authoritative source
[source]
host = "ldap.source.com"
port = 636
base = "dc=source,dc=com"
containers = [ "OU=Users", "OU=Terminated" ]
user = "cn=admin,dc=source,dc=com"
class = "inetOrgPerson"
name = "cn"

# Target containing orphans
[target]
host = "ldap.target.com"
port = 636
base = "cn=Users,dc=target,dc=com"
user = "cn=admin,dc=target,dc=com"
class = "inetOrgPerson"
name = "cn"
filter = "(employeeType=W)(employeeStatus=A)"
show_attribs = [ "employeeType", "employeeStatus", "modifyTimestamp" ]
